import { useState } from 'react'
import { ChevronRight, Plus } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '../api'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Empty, Err, fmtTime, PageHeader, TableSkeleton, useAsync } from '../ui'

export function Assignments() {
  const list = useAsync(() => api.listAssignments()); const groups = useAsync(() => api.listGroups()); const bundles = useAsync(() => api.listBundles()); const members = useAsync(() => api.listMembers()); const [adding, setAdding] = useState(false)
  async function remove(id: string) { try { await api.deleteAssignment(id); toast.success('授权已撤销'); list.reload() } catch (error) { toast.error((error as Error).message) } }
  return <><PageHeader title="授权策略" description="明确谁能获得什么，以及授权何时失效。" action={<Button onClick={() => setAdding(true)}><Plus />新增授权</Button>} /><Add open={adding} groups={groups.data?.groups ?? []} bundles={bundles.data?.bundles ?? []} members={members.data?.members ?? []} onOpenChange={setAdding} onDone={() => { setAdding(false); list.reload() }} /><Err msg={list.err} />{list.loading ? <TableSkeleton /> : !list.data?.assignments.length ? <Empty>还没有授权</Empty> : <Card className="overflow-hidden"><Table><TableHeader><TableRow><TableHead>授权目标</TableHead><TableHead>授予给</TableHead><TableHead>授权路径</TableHead><TableHead>有效期</TableHead><TableHead>创建时间</TableHead><TableHead /></TableRow></TableHeader><TableBody>{list.data.assignments.map((a) => <TableRow key={a.id}><TableCell>{a.group_name ? <Badge variant="accent">{a.group_name}</Badge> : <Badge>{a.bundle_name}</Badge>}</TableCell><TableCell>{a.subject_type === 'org' ? '全组织' : (a.subject_name || a.subject_id)}<div className="text-xs text-muted-foreground">{a.subject_type}</div></TableCell><TableCell><span className="flex items-center gap-1.5 text-muted-foreground">{a.group_name ? '权限组' : '单项'}<ChevronRight className="size-3" />{a.subject_type === 'org' ? '组织' : '成员'}</span></TableCell><TableCell>{a.expires_at ? <>{fmtTime(a.expires_at)}{a.expired && <Badge variant="destructive" className="ml-2">已到期</Badge>}</> : <span className="text-muted-foreground">永久</span>}</TableCell><TableCell className="whitespace-nowrap text-muted-foreground">{fmtTime(a.created_at)}</TableCell><TableCell className="text-right"><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="sm" className="text-destructive hover:text-destructive">撤销</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>撤销这条授权？</AlertDialogTitle><AlertDialogDescription>成员下次同步时将不再通过此授权获得对应内容。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => remove(a.id)}>确认撤销</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></TableCell></TableRow>)}</TableBody></Table></Card>}</>
}

function Add({ open, groups, bundles, members, onOpenChange, onDone }: { open: boolean; groups: { id: string; name: string }[]; bundles: { id: string; name: string }[]; members: { id: string; email: string }[]; onOpenChange: (v: boolean) => void; onDone: () => void }) {
  const [mode, setMode] = useState<'group' | 'bundle'>('group'); const [targetId, setTargetId] = useState(''); const [subject, setSubject] = useState<'org' | 'user'>('org'); const [subjectId, setSubjectId] = useState(''); const [expires, setExpires] = useState(''); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setErr(''); setBusy(true); try { await api.createAssignment({ ...(mode === 'group' ? { group_id: targetId } : { bundle_id: targetId }), subject_type: subject, ...(subject === 'user' ? { subject_id: subjectId } : {}), ...(expires ? { expires_at: new Date(expires).toISOString() } : {}) }); toast.success('授权已创建'); onDone() } catch (error) { setErr((error as Error).message) } finally { setBusy(false) } }
  const options = mode === 'group' ? groups : bundles
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>新增授权</DialogTitle><DialogDescription>常规场景优先授权权限组；单项授权用于临时例外。</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div><Label>授权目标</Label><Tabs value={mode} onValueChange={(v) => { setMode(v as 'group' | 'bundle'); setTargetId('') }} className="mt-2"><TabsList><TabsTrigger value="group">权限组</TabsTrigger><TabsTrigger value="bundle">单个内容</TabsTrigger></TabsList></Tabs><Select value={targetId} onValueChange={setTargetId}><SelectTrigger className="mt-3" aria-label="选择授权目标"><SelectValue placeholder="请选择…" /></SelectTrigger><SelectContent>{options.map((o) => <SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>授予给</Label><Select value={subject} onValueChange={(v) => setSubject(v as 'org' | 'user')}><SelectTrigger aria-label="授权对象类型"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="org">全组织</SelectItem><SelectItem value="user">指定成员</SelectItem></SelectContent></Select>{subject === 'user' && <Select value={subjectId} onValueChange={setSubjectId}><SelectTrigger aria-label="选择成员"><SelectValue placeholder="请选择成员…" /></SelectTrigger><SelectContent>{members.map((m) => <SelectItem key={m.id} value={m.id}>{m.email}</SelectItem>)}</SelectContent></Select>}</div><div className="space-y-2"><Label htmlFor="assignment-expires">到期时间</Label><Input id="assignment-expires" type="datetime-local" value={expires} onChange={(e) => setExpires(e.target.value)} /><p className="text-xs text-muted-foreground">留空为永久；外包、实习和临时支援建议设置。</p></div><Err msg={err} /><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>取消</Button><Button disabled={!targetId || (subject === 'user' && !subjectId) || busy}>{busy ? '授权中…' : '确认授权'}</Button></DialogFooter></form></DialogContent></Dialog>
}
