import * as React from 'react'
import { Download, ShieldAlert } from 'lucide-react'
import { api } from '../api'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Empty, Err, downloadCSV, fmtTime, PageHeader, TableSkeleton, toCSV, useAsync } from '../ui'

type Tab = 'all' | 'exec' | 'blocked' | 'stale'

export function Audit() {
  const state = useAuditState()
  return <><PageHeader title="审计事件" description="分发、执行与异常记录；仅保留治理所需元数据。" action={<Button variant="outline" onClick={state.exportCSV}><Download />导出 CSV</Button>} /><Tabs value={state.tab} onValueChange={(v) => state.setTab(v as Tab)}><TabsList className="mb-4 max-w-full overflow-x-auto"><TabsTrigger value="all">分发记录</TabsTrigger><TabsTrigger value="exec">执行记录</TabsTrigger><TabsTrigger value="blocked">下发受阻</TabsTrigger><TabsTrigger value="stale">长期未同步</TabsTrigger></TabsList></Tabs>{state.tab === 'exec' && <Info>只记录工具、仓库和文件等元数据；文件内容、diff、完整命令和提示词一律不上报。</Info>}{state.tab === 'blocked' && <Info>目标路径被成员自有的同名内容占用，因此跳过且不做改动。</Info>}{state.tab === 'stale' && <Info>用户级表示该成员所有设备都已掉队；设备级通常代表换机或闲置。</Info>}<AuditContent {...state} /></>
}

function Info({ children }: { children: React.ReactNode }) { return <div className="mb-4 flex gap-2 rounded-lg border bg-card px-4 py-3 text-sm text-muted-foreground"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-primary" />{children}</div> }

function useAuditState() {
  const [tab, setTab] = React.useState<Tab>('all'); const dist = useAsync(() => api.audit(tab === 'blocked' ? 'conflict_skipped' : undefined), [tab]); const exec = useAsync(() => api.executions(), [tab]); const stale = useAsync(() => api.staleMachines(), [tab])
  function exportCSV() { if (tab === 'stale') downloadCSV('stale-machines.csv', toCSV(stale.data?.machines ?? [], [['email','成员'],['hostname','设备'],['last_seen_at','最后活跃'],['days','已停(天)'],['user_level','用户级掉队']])); else if (tab === 'exec') { const rows = (exec.data?.entries ?? []).map((e) => ({ occurred_at:e.occurred_at,email:e.email,hostname:e.hostname,tool_name:e.tool_name ?? e.event_type,repo:e.summary.repo ?? '',file_path:e.summary.file_path ?? '',bash_command:e.summary.bash_command ?? '',lines_changed:e.summary.lines_changed ?? '' })); downloadCSV('executions.csv', toCSV(rows, [['occurred_at','时间'],['email','成员'],['hostname','设备'],['tool_name','工具'],['repo','仓库'],['file_path','文件'],['bash_command','命令'],['lines_changed','改动行数']])) } else downloadCSV(tab === 'blocked' ? 'blocked.csv' : 'distributions.csv', toCSV(dist.data?.entries ?? [], [['created_at','时间'],['email','成员'],['hostname','设备'],['bundle_name','内容'],['version','版本'],['action','动作'],['detail','详情']])) }
  return { tab, setTab, dist, exec, stale, exportCSV }
}

function AuditContent({ tab, dist, exec, stale }: ReturnType<typeof useAuditState>) {
  if (tab === 'exec') return <><Err msg={exec.err} />{exec.loading ? <TableSkeleton /> : !exec.data?.entries.length ? <Empty>暂无执行记录</Empty> : <Card className="overflow-hidden"><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>成员 / 设备</TableHead><TableHead>工具</TableHead><TableHead>动作</TableHead></TableRow></TableHeader><TableBody>{exec.data.entries.map((e,i) => <TableRow key={i}><TableCell className="whitespace-nowrap text-muted-foreground">{fmtTime(e.occurred_at)}</TableCell><TableCell>{e.email}<div className="text-xs text-muted-foreground">{e.hostname || '—'}</div></TableCell><TableCell><Badge>{e.tool_name || e.event_type}</Badge></TableCell><TableCell>{e.summary.file_path ? <>修改 <code className="rounded bg-muted px-1.5 py-0.5 text-xs">{e.summary.file_path}</code>{e.summary.lines_changed ? <span className="text-muted-foreground"> · {e.summary.lines_changed} 行</span> : null}</> : e.summary.bash_command ? <>执行 <code className="rounded bg-muted px-1.5 py-0.5 text-xs">{e.summary.bash_command}</code></> : <span className="text-muted-foreground">—</span>}{e.summary.repo && <div className="mt-1 text-xs text-muted-foreground">{e.summary.repo}</div>}</TableCell></TableRow>)}</TableBody></Table></Card>}</>
  if (tab === 'stale') return <><Err msg={stale.err} />{stale.loading ? <TableSkeleton /> : !stale.data?.machines.length ? <Empty>没有掉队的设备</Empty> : <Card className="overflow-hidden"><Table><TableHeader><TableRow><TableHead>成员</TableHead><TableHead>设备</TableHead><TableHead>最后活跃</TableHead><TableHead>已停</TableHead><TableHead>范围</TableHead></TableRow></TableHeader><TableBody>{stale.data.machines.map((m,i) => <TableRow key={i}><TableCell>{m.email}</TableCell><TableCell className="font-mono text-xs text-muted-foreground">{m.hostname || '—'}</TableCell><TableCell className="whitespace-nowrap text-muted-foreground">{fmtTime(m.last_seen_at)}</TableCell><TableCell>{m.days} 天</TableCell><TableCell>{m.user_level ? <Badge variant="destructive">用户级</Badge> : <Badge>设备级</Badge>}</TableCell></TableRow>)}</TableBody></Table></Card>}</>
  return <><Err msg={dist.err} />{dist.loading ? <TableSkeleton /> : !dist.data?.entries.length ? <Empty>暂无记录</Empty> : <Card className="overflow-hidden"><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>成员 / 设备</TableHead><TableHead>内容</TableHead><TableHead>动作</TableHead></TableRow></TableHeader><TableBody>{dist.data.entries.map((e,i) => <TableRow key={i}><TableCell className="whitespace-nowrap text-muted-foreground">{fmtTime(e.created_at)}</TableCell><TableCell>{e.email}<div className="font-mono text-xs text-muted-foreground">{e.hostname || '—'}</div></TableCell><TableCell>{e.bundle_name} <span className="font-mono text-xs text-muted-foreground">v{e.version}</span></TableCell><TableCell><Badge variant={e.action === 'conflict_skipped' ? 'warning' : e.action === 'remove' ? 'destructive' : 'success'}>{e.action}</Badge>{e.detail && <div className="mt-1 text-xs text-muted-foreground">{e.detail}</div>}</TableCell></TableRow>)}</TableBody></Table></Card>}</>
}
