import { useState, type ReactNode } from 'react'
import { ChevronDown, LogOut, Menu, Terminal } from 'lucide-react'
import type { UserInfo } from '@/api'
import { NAV_ITEMS, type Page } from '@/navigation'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'

function Nav({ page, onChange, compact = false }: { page: Page; onChange: (p: Page) => void; compact?: boolean }) {
  return <nav className="grid gap-1" aria-label="主要导航">{NAV_ITEMS.map(({ id, label, icon: Icon }) => {
    const button = <button key={id} type="button" aria-current={page === id ? 'page' : undefined} onClick={() => onChange(id)} className={cn('focus-ring flex h-10 w-full items-center gap-3 rounded-md px-3 text-left text-sm text-muted-foreground transition-colors duration-200 hover:bg-muted hover:text-foreground', page === id && 'bg-accent text-accent-foreground', compact && 'justify-center px-0')}><Icon className="size-4 shrink-0" /><span className={compact ? 'sr-only' : ''}>{label}</span>{page === id && !compact && <span className="ml-auto size-1.5 rounded-full bg-primary shadow-[0_0_8px_rgba(113,99,243,.7)]" />}</button>
    return compact ? <Tooltip key={id}><TooltipTrigger asChild>{button}</TooltipTrigger><TooltipContent side="right">{label}</TooltipContent></Tooltip> : button
  })}</nav>
}

export function AppShell({ user, page, onPageChange, onLogout, children }: { user: UserInfo; page: Page; onPageChange: (p: Page) => void; onLogout: () => void; children: ReactNode }) {
  const [mobileNavOpen, setMobileNavOpen] = useState(false)
  const title = NAV_ITEMS.find((item) => item.id === page)?.label ?? '控制台'
  return <TooltipProvider delayDuration={250}><div className="min-h-screen md:grid md:grid-cols-[72px_minmax(0,1fr)] lg:grid-cols-[232px_minmax(0,1fr)]">
    <aside className="hidden min-h-screen flex-col border-r bg-card p-3 md:flex lg:p-4"><div className="mb-6 flex h-9 items-center justify-center gap-2 lg:justify-start lg:px-2"><span className="grid size-8 place-items-center rounded-lg bg-primary text-white shadow-[0_0_20px_rgba(113,99,243,.38)]"><Terminal className="size-4" /></span><span className="hidden font-semibold lg:block">ITH5</span><span className="ml-auto hidden font-mono text-[10px] text-muted-foreground lg:block">v0.x</span></div><div className="mb-2 hidden px-3 text-[10px] font-medium uppercase tracking-[.15em] text-muted-foreground lg:block">Control plane</div><div className="hidden lg:block"><Nav page={page} onChange={onPageChange} /></div><div className="lg:hidden"><Nav page={page} onChange={onPageChange} compact /></div>
      <div className="mt-auto hidden rounded-lg bg-muted p-3 lg:block"><div className="flex items-center gap-2 text-xs font-medium"><span className="size-1.5 rounded-full bg-success shadow-[0_0_8px_rgba(19,133,101,.45)]" />服务正常</div><p className="mt-1 text-xs text-muted-foreground">控制平面已连接</p></div><DropdownMenu><DropdownMenuTrigger asChild><button className="focus-ring mt-3 flex w-full items-center gap-2 rounded-md p-2 text-left hover:bg-muted"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-700 text-xs font-medium text-white">{user.email.slice(0, 1).toUpperCase()}</span><span className="hidden min-w-0 flex-1 lg:block"><span className="block truncate text-xs font-medium">{user.email}</span><span className="block text-[11px] text-muted-foreground">{user.role}</span></span><ChevronDown className="hidden size-3.5 text-muted-foreground lg:block" /></button></DropdownMenuTrigger><DropdownMenuContent side="top" align="start"><DropdownMenuLabel>{user.email}</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onSelect={onLogout}><LogOut />退出登录</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    </aside>
    <div className="min-w-0"><header className="sticky top-0 z-30 flex h-16 items-center border-b bg-background/95 px-4 backdrop-blur sm:px-6 lg:px-8"><Sheet open={mobileNavOpen} onOpenChange={setMobileNavOpen}><SheetTrigger asChild><Button variant="outline" size="icon" className="mr-3 md:hidden" aria-label="打开导航"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-72"><SheetTitle className="mb-6 flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary text-white"><Terminal className="size-4" /></span>ITH5</SheetTitle><Nav page={page} onChange={(nextPage) => { onPageChange(nextPage); setMobileNavOpen(false) }} /></SheetContent></Sheet><span className="text-muted-foreground">工作区&nbsp; / &nbsp;<strong className="font-medium text-foreground">{title}</strong></span><div className="ml-auto md:hidden"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="用户菜单"><span className="grid size-8 place-items-center rounded-full bg-slate-700 text-xs text-white">{user.email.slice(0, 1).toUpperCase()}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{user.email}</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onSelect={onLogout}><LogOut />退出登录</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main className="mx-auto w-full max-w-[1440px] p-4 sm:p-6 lg:p-8">{children}</main></div>
  </div></TooltipProvider>
}
